### ISSUE TITLE
Error when creating products after disabling Tax module on clean magento 1.9.3.7 installation

### ISSUE THREAD

**Issue by Nikita-S-Doroshenko** [Zookal/magento-mock#14]
Error shows on creating/editing Simple/Virtual/Bundled products.
```
a:5:{i:0;s:88:"Invalid method Zookal_Mock_Model_Mocks_Mage_Config::_isReturnFalse Cannot print args ...";i:1;s:6857:"#0 /usr/local/opt/magento/app/code/core/M
#1 /usr/local/opt/magento/app/code/core/Mage/Tax/Helper/Data.php(193): Zookal_Mock_Model_Mocks_Mage_Config->priceIncludesTax(Object(Mage_Core_Model_Store))
#2 /usr/local/opt/magento/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Helper/Form/Price.php(56): Mage_Tax_Helper_Data->priceIncludesTax(Object(Mage_Cor
#3 /usr/local/opt/magento/lib/Varien/Data/Form/Element/Abstract.php(179): Mage_Adminhtml_Block_Catalog_Product_Helper_Form_Price->getAfterElementHtml()
#4 /usr/local/opt/magento/app/code/core/Mage/Adminhtml/Block/Catalog/Form/Renderer/Fieldset/Element.php(189): Varien_Data_Form_Element_Abstract->getElementHtm
#5 /usr/local/opt/magento/app/design/adminhtml/default/default/template/catalog/form/renderer/fieldset/element.phtml(47): Mage_Adminhtml_Block_Catalog_Form_Re
#6 /usr/local/opt/magento/app/code/core/Mage/Core/Block/Template.php(241): include('/usr/local/opt/...')
#7 /usr/local/opt/magento/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#8 /usr/local/opt/magento/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#9 /usr/local/opt/magento/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#10 /usr/local/opt/magento/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#11 /usr/local/opt/magento/app/code/core/Mage/Adminhtml/Block/Widget/Form/Renderer/Fieldset/Element.php(52): Mage_Core_Block_Abstract->toHtml()
#12 /usr/local/opt/magento/lib/Varien/Data/Form/Element/Abstract.php(223): Mage_Adminhtml_Block_Widget_Form_Renderer_Fieldset_Element->render(Object(Mage_Admi
#13 /usr/local/opt/magento/lib/Varien/Data/Form/Element/Text.php(46): Varien_Data_Form_Element_Abstract->getHtml()
#14 /usr/local/opt/magento/lib/Varien/Data/Form/Element/Abstract.php(233): Varien_Data_Form_Element_Text->getHtml()
#15 /usr/local/opt/magento/lib/Varien/Data/Form/Element/Fieldset.php(90): Varien_Data_Form_Element_Abstract->toHtml()
#16 /usr/local/opt/magento/app/design/adminhtml/default/default/template/widget/form/renderer/fieldset.phtml(49): Varien_Data_Form_Element_Fieldset->getChildr
#17 /usr/local/opt/magento/app/code/core/Mage/Core/Block/Template.php(241): include('/usr/local/opt/...')
#18 /usr/local/opt/magento/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#19 /usr/local/opt/magento/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#20 /usr/local/opt/magento/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#21 /usr/local/opt/magento/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#22 /usr/local/opt/magento/app/code/core/Mage/Adminhtml/Block/Widget/Form/Renderer/Fieldset.php(51): Mage_Core_Block_Abstract->toHtml()
#23 /usr/local/opt/magento/lib/Varien/Data/Form/Element/Abstract.php(223): Mage_Adminhtml_Block_Widget_Form_Renderer_Fieldset->render(Object(Varien_Data_Form_
#24 /usr/local/opt/magento/lib/Varien/Data/Form/Element/Abstract.php(233): Varien_Data_Form_Element_Abstract->getHtml()
#25 /usr/local/opt/magento/lib/Varien/Data/Form.php(244): Varien_Data_Form_Element_Abstract->toHtml()
#26 /usr/local/opt/magento/lib/Varien/Data/Form.php(256): Varien_Data_Form->toHtml()
#27 /usr/local/opt/magento/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(108): Varien_Data_Form->getHtml()
#28 /usr/local/opt/magento/app/design/adminhtml/default/default/template/widget/form.phtml(28): Mage_Adminhtml_Block_Widget_Form->getFormHtml()
#29 /usr/local/opt/magento/app/code/core/Mage/Core/Block/Template.php(241): include('/usr/local/opt/...')
#30 /usr/local/opt/magento/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#31 /usr/local/opt/magento/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#32 /usr/local/opt/magento/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#33 /usr/local/opt/magento/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#34 /usr/local/opt/magento/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Edit/Tabs.php(79): Mage_Core_Block_Abstract->toHtml()
#35 /usr/local/opt/magento/app/code/core/Mage/Core/Block/Abstract.php(297): Mage_Adminhtml_Block_Catalog_Product_Edit_Tabs->_prepareLayout()
#36 /usr/local/opt/magento/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#37 /usr/local/opt/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('adminhtml/catal...', 'product_tabs')
#38 /usr/local/opt/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('adminhtml/catal...', 'product_tabs')
#39 /usr/local/opt/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Objec
#40 /usr/local/opt/magento/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#41 /usr/local/opt/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#42 /usr/local/opt/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#43 /usr/local/opt/magento/app/code/core/Mage/Adminhtml/Controller/Action.php(285): Mage_Core_Controller_Varien_Action->loadLayout(Array, true, true)
#44 /usr/local/opt/magento/app/code/core/Mage/Adminhtml/controllers/Catalog/ProductController.php(250): Mage_Adminhtml_Controller_Action->loadLayout(Array)
#45 /usr/local/opt/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Catalog_ProductController->editAction()
#46 /usr/local/opt/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#47 /usr/local/opt/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Contr
#48 /usr/local/opt/magento/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#49 /usr/local/opt/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#50 /usr/local/opt/magento/index.php(83): Mage::run('', 'store')
#51 {main}";s:3:"url";s:80:"/index.php/admin/catalog_product/edit/id/1/key/4caeb009066e1ea9674b1f89d2972f07/";s:11:"script_name";s:10:"/index.php";s:4:"skin";
```

**Comment by SchumacherFM** [comment]
Can you send a Pull Request to mock the missing method `priceIncludesTax`? 

You should try it in your installation if this method `priceIncludesTax` is the correct one.

**Comment by Nikita-S-Doroshenko** [comment]
Sorry, I miss the ending of the first zero line:

`a:5:{i:0;s:88:"Invalid method Zookal_Mock_Model_Mocks_Mage_Config::_isReturnFalse Cannot print args ...";i:1;s:6857:"#0 /usr/local/opt/magento/app/code/core/Mage/Tax/Helper/Data.php(193): Zookal_Mock_Model_Mocks_Abstract->__call('priceIncludesTa...', Array)`

Unfortunately I'm not a Magento developer and event I don't know PHP, I spend a few hours trying to solve your comment and experiment with making mock, but my knowledge don't allow me fix this solution at that moment.
Will appreciate if you can take a look in this issue and guide me how I can make solution.
